# Site settings
name: codingaholic
title: Codingaholic
email: codingaholic@gmail.com
description: ""
baseurl: ""

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title

paginate: 12

#analytics
google_analytics_tracking_id: UA-51592308-1 
