# Site settings
name: codingaholic
title: Codingaholic
email: codingaholic@gmail.com
description: ""
baseurl: "http://codingaholic.com/"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title

paginate: 12
